### ISSUE TITLE
Bug with "Mask"

### ISSUE THREAD

**Issue by cortek** [aresdevo/animaide#46] opened 2021-03-31 09:37 UTC
I can't disable mask.
Activate or disable doesn't help. Only in one project.
![Captusdre](https://user-images.githubusercontent.com/11559699/113124050-cd3d8500-921d-11eb-9d63-cd1b264a016d.PNG)

**Comment by aresdevo** [comment] 2021-04-01 02:21
Oh!!... I think I maybe know what the problem is:

The animOffset temporarily used Blender preview range to visualize the mask. In your case for some reason (some kind of error I would be interested in knowing about), the Blender preview got the same values as the animOffset mask you created after you de-activated the tool. If that is what is going on the solution is very simple:

Deactivate the little clock at the right of the timeline.

<img width="551" alt="Screen Shot 2021-03-31 at 7 08 00 PM" src="https://user-images.githubusercontent.com/16739268/113234154-95523400-9255-11eb-89e2-dcff40362a57.png">

<img width="551" alt="Screen Shot 2021-03-31 at 7 07 40 PM" src="https://user-images.githubusercontent.com/16739268/113234178-a00cc900-9255-11eb-923a-fee545f279a6.png">

Again, I'm guessing here, but if this is what is going on you can set the start and end of your preview range there, or set the  start and end the range of your animation here to reset your timeline as you had it:

<img width="561" alt="Screen Shot 2021-03-31 at 7 09 36 PM" src="https://user-images.githubusercontent.com/16739268/113234298-d9453900-9255-11eb-9b5c-7f4ddac9fe47.png">

**Comment by aresdevo** [comment] 2021-04-16 01:40
please let me know if this was your issue

**Comment by jfixit** [comment] 2021-07-25 20:55
I am having an issue where, after I use the mask and I turn it off, anytime I move a bone to create a new keyframe all the other keyframes move with it.  In other words, all of the f-curves become straight lines and I can't animate anymore.  I had to uninstall the addon for normal keyframe function to come back.  Not sure if I was using the addon incorrectly.
![animaide](https://user-images.githubusercontent.com/86990001/126913224-b5ba280d-9342-4c4e-a9be-4309f6b50939.gif)

**Comment by aresdevo** [comment] 2021-08-13 19:32
@jfixit , that looks to be the normal behavior of the anim-offset tool. If anim-offset is on, any change you make propagates to the entire animation. The way to solve that is by turning off that tool.

Please try it again and let me know if it works

**Comment by aresdevo** [comment] 2021-08-30 20:58
Can you let me know if it was anim-offset that was causing the confusion or if is a bug

**Comment by aresdevo** [comment] 2022-02-16 05:36
Closing this since it doesn't look like a bug

**Closed by aresdevo** 2022-02-16 05:36 UTC
Labels: bug
