### ISSUE TITLE
Anim transform doesnt work at all in some cases.

### ISSUE THREAD

**Issue by lucianomunoz** [aresdevo/animaide#24] opened 2020-05-06 09:19 UTC
I dont know what triggers it, bot sometimes anim transform can be on and no matter what you do the curves dont get affected.

**Comment by wbmoss** [comment] 2020-05-09 22:40
This comment is for the author, the fix is to replace "return" with "continue" in manget.py on line 61 and 80.
![animaide_fix](https://user-images.githubusercontent.com/28886285/81486695-8d943600-9224-11ea-81a2-02a9398bdf3b.gif)

**Comment by Irmitya** [comment] 2020-05-10 05:39
I'd rather
```fcurves = getattr(action, 'fcurves', list())```
and remove the fcurve check.
The `for` will always run next and if it has nothing to iterate on, then it'll `continue`. 
The bone `return` swap is still mandatory.

Can also place this alt `getattr`, on the `for` line, because the `fcurves` var isn't re-used.
```for fcurve in getattr(action, 'fcurves', list()):```

**Comment by lucianomunoz** [comment] 2020-08-03 13:18
does any of you want fork the add-on and keep developing it? this would be a great thing if it would be working and improved :(

**Comment by Irmitya** [comment] 2020-08-03 15:30
I'd do it if I were paid.

**Comment by aresdevo** [comment] 2020-12-18 20:59
Sorry I have abandoned this project. This year has been crazy. I had to deal with some personal issues but things are looking better at the moment. 

<I'd do it if I were paid.>
@Irmitya, that kind of comment is not constructive at all.

I will go through the code again and try addressing the bugs, but maybe this addon won't be a necessity anymore since somebody is adding a [similar tool in Blender](https://developer.blender.org/T81836). You can download there a build for Linux and Windows.

**Comment by lucianomunoz** [comment] 2020-12-18 21:02
hey @aresdevo thank you for such cool addon!, maybe would be cool and less problematic if you stripped it down to just the "anim transform" feature only since as you said a similar tool is being created in blender. The anim transform is a couple of steps further.
also i'd love to invite you to join us in the next animation meeting, your input would be greatly appreaciated as you're an animator too :)

**Comment by aresdevo** [comment] 2020-12-18 22:07
hmm, interesting... Part of the issue is that both tools collide at times. Maybe they should have always been too different addons.

I would like to be part of that meeting, please send me any information at aresdevo@gmail.com

**Comment by aresdevo** [comment] 2021-01-18 16:44
I have spent a few weeks going through the code enhancing the add-on and fixing bugs. Hopefully, I have addressed most of them. 

This specific bug seems to be addressed by one of @Irmitya commits.

I just publish it and call it version 1.0. Please let me know how things work for you.

**Closed** 2021-01-26 01:54 UTC
Labels: bug

**Comment by mahreeoocedev01** [comment] 2021-02-02 04:13
Sorry for re-opening the discussion, but I'm still experiencing the bug. I'll attach a file with a rig and two actions - the "anim offset - without mask" tool is working for one of them and not for the other (named them working and not_working). 

The rig is a modified rigify rig.
In the "not_working" action, the only bone that can be offset is the torso control (the big cube at the hips). 
In the "working" action, every bone works fine.

The one difference I can see between the two actions is that the non-working one has a few invalid channels in the graph editor, which I left on purpose, as they may be a hint (they were added by the wiggle bone addon, if I recall). But even bones with only valid channels still don't get offset.
Even if deleting the invalid channels, the anim offset still doesn't work.

I hope it's enough to get a few clues for the problem.

Thanks for all your work on this addon!

[animaide_anim_offset_bone_movement_bug.zip](https://github.com/aresdevo/animaide/files/5908586/animaide_anim_offset_bone_movement_bug.zip)
