### ISSUE TITLE
Error using Delete Key Type when character is linked & using nla

### ISSUE THREAD

**Issue by lucianomunoz** [aresdevo/animaide#45] opened 2021-03-30 05:39 UTC
I know it's a specific case but the more the NLA becomes useful, the more common this will be
So this is a shot where the character has been linked, rig proxies have been created and the nla is being used, i get this error when trying to delete key types 

![image](https://user-images.githubusercontent.com/5134226/112939016-a9494900-9122-11eb-91f5-b6bd3a492cc7.png)

![image](https://user-images.githubusercontent.com/5134226/112938985-9c2c5a00-9122-11eb-9f91-9b1d68f3fa40.png)

**Comment by aresdevo** [comment] 2021-04-01 02:04
Yes, I need to test with nla and with linked characters. I'll try to reproduce this error. Thanks for reporting this

**Comment by aresdevo** [comment] 2021-08-30 18:31
ok... I'm back... I can dedicate time to this now... I will let you know what I find out.

Sorry for the delay.

**Comment by RiggingDojoAdmin** [comment] 2022-02-14 05:37
It seems like the Anim Offset also has an issue with the NLA, where it seems to try and move all the keys for everything in the NLA action instead of just the selected bone...imploding the rig.

**Comment by RiggingDojoAdmin** [comment] 2022-02-14 16:42
The workaround from the animator who found this...had a workaround. 

"Move action to frame 1, edit thing and move back this action, for example with combine 2 non in place walking animations; make action from walk animation, in the last frame of the animation go to POSE MODE, select the main bone (pelvis here), click CTRL + C to copy the coordinates of this bone, duplicate the action with this animation, move this duplicate to the layer higher in NLA so that it starts start from frame 1, click TAB on this duplicate action to edit it, while on frame 1 select the main bone (pelvis), click Activate in the addon anim offset, press CTRL + V to change its coordinates to those we have in memory, click Deactivate in the addon anim offset , again TAB on the action to close editing, move it in the NLA so that it starts after the first. This way we have a smooth extension of the non in place walking animation."

Not sure why having the action start on frame 1 is making the tool work or not but that might help track down the bug.

**Comment by aresdevo** [comment] 2022-02-16 08:44
Hey @lucianomunoz, I hope you are still following this addon. I finally addressed this issue. I thought it had something to do with NLA but it was actually an error in the KeyManager code.

**Comment by aresdevo** [comment] 2022-02-16 08:46
@RiggingDojoAdmin... hopefully, that NLA workaround is a thing of the past.

**Comment by aresdevo** [comment] 2022-02-16 16:43
Closing this issue since it seems to be resolved. @lucianomunoz, if you are still following, open a new issue if there is anything else you find. Thank you so much for your help

**Closed by aresdevo** 2022-02-16 16:43 UTC
Labels: bug
