### ISSUE TITLE
Anim Offset Feature Request

### ISSUE THREAD

**Issue by etufoz** [aresdevo/animaide#51] opened 2021-08-27 07:58 UTC
Hi there, coming from Maya and animBot, your addon has been a real life and time-saver, so thank you so much for this!

I've been working with mocap quite a bit lately and found Anim Offset indespensible, however, as I want to apply the offsets to the whole animation, I haven't been using the masking tool and assigned Anim Offset to my Quick Favourites in the viewport.  Now this doesn't happen often, but it does happen that i leave Anim Offset activated and continue to work, only later realising I've totally messed up my animation.  I'm not sure if I had Anim Offset on/off, but trying to undo further broke the animation.

My request is for something in the viewport to be visible, maybe just text or even better, like a viewport border - with the option to change colour and opacity.  Please see my attached image as reference.

![animOffset_border](https://user-images.githubusercontent.com/52486298/131092554-65294002-fbf2-4a6f-84c8-8b7847e5f199.jpg)

**Comment by aresdevo** [comment] 2021-08-28 21:09
Oh!... sorry you lost work because of the addon. I understand your suggestion. I'll think of something to warn the user the addon is active.

Thanks for the feedback.

**Comment by aresdevo** [comment] 2021-08-28 21:12
I'll also check if the addon does something to the "undo" system.

**Comment by etufoz** [comment] 2021-08-29 04:31
Thanks for the response!  I didn't lose much work, plus the time I save with all the other features easily makes up what I can do without the addon.

I'm not 100% sure how to reproduce it, but I was also working with NLA strips (pressing Tab to edit). If I run into the issue again, I will document it and post an update here.

**Comment by etufoz** [comment] 2021-08-29 10:12
Hi again, so I think the issue is not the Undo, but working NLA strips at the edit level.  Please see the GIF, just the first 15s is where I encounter the issue. Some controls just get offset.  If I don't undo far back enough, some controls will only be slightly offset, but noticeable enough, for example the feet controls would be a bit rotated.
https://imgur.com/6YWuvqx

**Comment by aresdevo** [comment] 2021-08-29 22:58
hmmm... I honestly didn't consider the NLA when coding the addon.  I can see why it would create problems. I need to look into that. Issue #45 also reports a bug related to NLA ("anim-offset" used to be called "anim-ransform"). 

In regard to your suggestion of having something on the interface that warns the user, I like the red border but don't know how to do that yet. I think I'm going to add a text on the 3D View, but in the meantime, you can go to the addon preference and put anim-offset on the header instead of on the panel, that way you can see on the timeline header when anim-offset is active or not (it also shows on the graph editor and on the dope sheet).

**Comment by etufoz** [comment] 2021-08-30 06:53
Have you considered having a donation option on Gumroad?  It's would be well deserved :)

Thanks, I've put the Header option on, just have to be a bit more conscious of it, and not get too zoned out.

So, I saw some people doing proposals on RCS for a similar viewport change for Local View and Auto-Keyframe.

I dug around a bit in Preferences> Themes and the "easiest" win (because I don't know much about developing addons at all!), would be to store user settings for Graph/Dope Sheet Editors> Theme Space> Header, and change that colour when Anim Offset is active.
![image](https://user-images.githubusercontent.com/52486298/131297764-3f2aa972-3757-42fc-acd2-83f08c8787bd.png)

**Comment by aresdevo** [comment] 2021-08-30 16:46
Wow, thanks a lot for all that information.

I didn't know about Gumroad. Donations could be an interesting option. I'll look into that. 
I appreciate your feedback and comments. I'm not a programmer, I'm just an animator learning how to code and used this project to learn while doing something useful, but never knew if I was going to be able to achieve it. It is rewarding just knowing that my efforts are making someone's life better.

The information you found is actually very useful. I had already added a text to the 3D view and the info here is very similar but with the extra of adding color to the header. I already added that to the addon, but have not pushed the change to GitHub yet because there is a bug I have not been able to solve. At the moment the header changes color when I activate anim-offset, and it goes back to the color it had once anim-offset is off as it should, but if I quit Blender while anim-offset is active it doesn't change the header's color back before it quits. So, when I open Blender again the headers have the new color as a default. I have tried different things but so far have not been successful.

I will let you know when I find a solution.

**Comment by etufoz** [comment] 2021-08-30 16:59
It's really impressive what you've been able to create whilst not being a programmer.  My programming knowledge is limited to copying and pasting from stackoverflow and replacing variables.

At the risk of suggesting something you may have already tried, what if the offset-button first calls the original default colour, sets it to that and then changes to the "on-colour"?  I don't know what would happen if you quit while it's still active though.

**Comment by aresdevo** [comment] 2021-08-30 17:11
Well, right now anim-offset is doing something kind of similar to what you describe: 


1. Stores the current color of the headers
2. Changes the color to the new one.

Then, when it gets deactivated, puts the stored color back on the headers.

The function that does the deactivation also runs when Blender quits. The problem is that when Blender quits it saves the preferences before running my functions. The solution would be to change that order, but don't know how to do it yet.

**Comment by etufoz** [comment] 2021-08-30 17:15
Oh, that sounds like a challenge!  Man, I should get more into
programming.  It feels good to solve these issues.

**Comment by aresdevo** [comment] 2021-08-30 17:37
I've been interested in learning to code for a while now, so I've been reading books and watching tutorials, but they usually make you create useless programs so I decided to try something in Blender. My first attempts were not very successful but after a while, they started getting better. The issue with coding is that you not only need to learn the rules of the language (in this case Python), in a sense that is the easiest part, you also need to learn how all the different modules of the thing you are working on with works (in this case Blender). [This curse](https://cloud.blender.org/training/scripting-for-artists/) has helped me a lot, but I have to confess I have spent a lot of time going through the [API documentation](https://docs.blender.org/api/current/index.html). It can be challenging and frustrating at times but when you finally make it work it is super rewarding. Feels like solving a puzzle

**Comment by aresdevo** [comment] 2021-08-30 17:57
By the way, excuse my English. I have been living in the USA for 20 years now but still don't speak or write the language as I should after all those years :P

**Comment by etufoz** [comment] 2021-08-30 18:56
To be honest, I didn't notice any problems with your English :)
Thanks very much for the share.  I'm working through some other courses (not coding) at the moment, so once I get through that and don't have too much work, I will get stuck into this properly!  My office is moving to a full Blender pipeline, and it definitely has it's challenges so I want to make some pipeline tools to help the team.

**Comment by aresdevo** [comment] 2021-08-31 22:37
Ok... I think I found a solution. 
I suspended the option to autosave the preferences when anim_offset is active and activate it again when is off. Hopefully, that doesn't make some people angry :P.
I pushed a new version to Github so you can download it and try it. Let me know if it works for you.

**Comment by etufoz** [comment] 2021-09-01 07:09
That's amazing man! Let me give it a go through the day.

**Comment by etufoz** [comment] 2021-09-01 12:09
Hi, those changes really help from a visual que standpoint!  Personally I would put the text notification in the bottom center of the screen.
I don't know if it's just an issue I'm having my side, but when Anim Offset is active and I try to move anything, the oboject or bone just keeps snapping to it's original keyed transforms.
![kNMnam2zqJ](https://user-images.githubusercontent.com/52486298/131652778-28a922c2-ad54-4067-9e0c-dcaea694211a.gif)

**Comment by aresdevo** [comment] 2021-09-01 18:37
My mistake, I was trying something out and by mistake disabled a line that makes anim_offset work. There is a new version that should fix it

**Comment by aresdevo** [comment] 2021-09-01 18:42
I thought about putting the text in the bottom center, but that requires a little more code to let the addon know the dimension of the 3D view. I'll do that later, just wanted to make this work first.

**Comment by aresdevo** [comment] 2021-09-01 18:43
let me know if it works

**Comment by etufoz** [comment] 2021-09-02 07:10
So far, so good :) Thank you

**Comment by aresdevo** [comment] 2022-02-16 17:07
I'm closing this one. let me know if you have any more suggestions or find any issues. Thank you.

**Closed by aresdevo** 2022-02-16 17:07 UTC
Labels: enhancement
